import "./globals.css";
import Navbar from "./Components/Navbar";
import Footer from "./Components/Footer";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import Providers from "./Provider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body>
        <Providers>
          <Navbar />
          {children}
          <Footer />
       </Providers>
      </body>
    </html>
  );
}
